/*
 * Copyright (c) 2013, Jeremy Brooks
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the FreeBSD Project.
 */
package net.jeremybrooks.readsy.gui;

import net.jeremybrooks.readsy.Readsy;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.WindowConstants;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;


/**
 * The about dialog box.
 * It should display the splash screen logo, the version, and a brief message
 * including contact information and license.
 *
 * @author Jeremy Brooks
 */
public class AboutDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 3396224981175261460L;

	private ResourceBundle bundle = ResourceBundle.getBundle("localization.about_dialog");

	/**
	 * Creates new form AboutDialog
	 *
	 * @param parent parent of this dialog.
	 * @param modal  should this be presented modally.
	 */
	public AboutDialog(Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		this.versionLabel.setText(this.versionLabel.getText() + " " + Readsy.VERSION);

		// TODO: Verify that this data shows up correctly
		// add some data to credits
		StringBuilder sb = new StringBuilder(this.creditsTextArea.getText());
		if (Readsy.getMainWindow().getTabList().size() > 0) {
			sb.append(bundle.getString("installedFiles"));
			for (TabPanel tp : Readsy.getMainWindow().getTabList()) {
				sb.append(tp.getStats()).append('\n');
			}
		} else {
			sb.append(bundle.getString("nothingInstalled"));
		}
		this.creditsTextArea.setText(sb.toString());

		// put the cursor at the beginning of the about stuff
		this.creditsTextArea.setCaretPosition(0);
		this.licenseTextArea.setCaretPosition(0);
		this.helpTextArea.setCaretPosition(0);

		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		Dimension windowSize = this.getPreferredSize();
		setLocation(screenSize.width / 2 - (windowSize.width / 2),
				screenSize.height / 2 - (windowSize.height / 2));
	}


	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		ResourceBundle bundle = bundle = this.bundle;;
		panel1 = new JPanel();
		iconLabel = new JLabel();
		versionLabel = new JLabel();
		jTabbedPane1 = new JTabbedPane();
		jScrollPane3 = new JScrollPane();
		helpTextArea = new JTextArea();
		jScrollPane1 = new JScrollPane();
		creditsTextArea = new JTextArea();
		jScrollPane2 = new JScrollPane();
		licenseTextArea = new JTextArea();
		panel2 = new JPanel();
		okButton = new JButton();

		//======== this ========
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(bundle.getString("this.title"));
		setAlwaysOnTop(true);
		setModal(true);
		Container contentPane = getContentPane();
		contentPane.setLayout(new BorderLayout());

		//======== panel1 ========
		{
			panel1.setLayout(new BorderLayout());

			//---- iconLabel ----
			iconLabel.setIcon(new ImageIcon(getClass().getResource("/images/icon500x300.png")));
			panel1.add(iconLabel, BorderLayout.CENTER);

			//---- versionLabel ----
			versionLabel.setText(bundle.getString("versionLabel.text"));
			panel1.add(versionLabel, BorderLayout.SOUTH);
		}
		contentPane.add(panel1, BorderLayout.NORTH);

		//======== jTabbedPane1 ========
		{

			//======== jScrollPane3 ========
			{

				//---- helpTextArea ----
				helpTextArea.setColumns(20);
				helpTextArea.setEditable(false);
				helpTextArea.setLineWrap(true);
				helpTextArea.setRows(5);
				helpTextArea.setText(bundle.getString("helpTextArea.text"));
				helpTextArea.setWrapStyleWord(true);
				jScrollPane3.setViewportView(helpTextArea);
			}
			jTabbedPane1.addTab(bundle.getString("jScrollPane3.tab.title"), jScrollPane3);

			//======== jScrollPane1 ========
			{

				//---- creditsTextArea ----
				creditsTextArea.setEditable(false);
				creditsTextArea.setLineWrap(true);
				creditsTextArea.setRows(10);
				creditsTextArea.setText(bundle.getString("creditsTextArea.text"));
				creditsTextArea.setWrapStyleWord(true);
				creditsTextArea.setMargin(new Insets(3, 3, 3, 3));
				jScrollPane1.setViewportView(creditsTextArea);
			}
			jTabbedPane1.addTab(bundle.getString("jScrollPane1.tab.title"), jScrollPane1);

			//======== jScrollPane2 ========
			{

				//---- licenseTextArea ----
				licenseTextArea.setEditable(false);
				licenseTextArea.setLineWrap(true);
				licenseTextArea.setRows(15);
				licenseTextArea.setText(bundle.getString("licenseTextArea.text"));
				licenseTextArea.setWrapStyleWord(true);
				jScrollPane2.setViewportView(licenseTextArea);
			}
			jTabbedPane1.addTab(bundle.getString("jScrollPane2.tab.title"), jScrollPane2);
		}
		contentPane.add(jTabbedPane1, BorderLayout.CENTER);

		//======== panel2 ========
		{
			panel2.setLayout(new FlowLayout(FlowLayout.RIGHT));

			//---- okButton ----
			okButton.setText(bundle.getString("okButton.text"));
			okButton.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					jButton1ActionPerformed();
				}
			});
			panel2.add(okButton);
		}
		contentPane.add(panel2, BorderLayout.SOUTH);
		pack();
		setLocationRelativeTo(getOwner());
	}// </editor-fold>//GEN-END:initComponents


	private void jButton1ActionPerformed() {//GEN-FIRST:event_jButton1ActionPerformed
		this.setVisible(false);
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JPanel panel1;
	private JLabel iconLabel;
	private JLabel versionLabel;
	private JTabbedPane jTabbedPane1;
	private JScrollPane jScrollPane3;
	private JTextArea helpTextArea;
	private JScrollPane jScrollPane1;
	private JTextArea creditsTextArea;
	private JScrollPane jScrollPane2;
	private JTextArea licenseTextArea;
	private JPanel panel2;
	private JButton okButton;
	// End of variables declaration//GEN-END:variables
}
