/*
 * readsy - read something new every day <http://jeremybrooks.net/readsy>
 *
 * Copyright (c) 2013-2021  Jeremy Brooks
 *
 * This file is part of readsy.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package net.jeremybrooks.readsy.gui;

import net.jeremybrooks.readsy.PropertyManager;
import org.apache.commons.lang3.StringUtils;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.io.File;
import java.util.List;
import java.util.ResourceBundle;

import static net.jeremybrooks.readsy.Constants.WINDOW_IMAGE;

/**
 * Allow the user to set various preferences.
 * Settings will be saved for future use.
 *
 * @author Jeremy Brooks
 */
public class PreferencesDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 2431764287936009269L;
	private final ResourceBundle bundle = ResourceBundle.getBundle("localization.preferences");
	private MainWindow mainWindow;

  private void btnChangeDirActionPerformed() {
    JFileChooser jfc = new JFileChooser();
    jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    jfc.setMultiSelectionEnabled(false);
    if (StringUtils.isNotEmpty(txtFileDir.getText())) {
      jfc.setCurrentDirectory(new File(txtFileDir.getText()));
    }

    int selection = jfc.showOpenDialog(this);
    if (selection == JFileChooser.APPROVE_OPTION) {
      String newDir = jfc.getSelectedFile().getAbsolutePath();
      txtFileDir.setText(newDir);
      PropertyManager propertyManager = PropertyManager.getInstance();
      propertyManager.setProperty(PropertyManager.READSY_FILE_DIRECTORY, newDir);
      if (mainWindow != null) {
        mainWindow.createTabs();
      }
    }
  }

	public PreferencesDialog(Frame parent, boolean modal) {
		super(parent, modal);
    if (parent instanceof MainWindow) {
      this.mainWindow = (MainWindow)parent;
    }

		initComponents();
		this.cbxUpdates.setSelected(PropertyManager.getInstance().getPropertyAsBoolean(PropertyManager.PROPERTY_CHECK_FOR_UPDATES));
    /* The initial font size shown in the dialog. */
    int initialFontSize = PropertyManager.getInstance().getPropertyAsInt(PropertyManager.PROPERTY_FONT_SIZE);
		this.cmbFont.setSelectedItem(Integer.toString(initialFontSize));
		this.txtFileDir.setText(PropertyManager.getInstance().getProperty(PropertyManager.READSY_FILE_DIRECTORY));
		setIconImage(WINDOW_IMAGE);
		getRootPane().setDefaultButton(this.btnOk);
	}

	/*
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    ResourceBundle bundle = this.bundle;
    panel2 = new JPanel();
    jPanel1 = new JPanel();
    cbxUpdates = new JCheckBox();
    jPanel3 = new JPanel();
    textArea2 = new JTextArea();
    panel3 = new JPanel();
    cmbFont = new JComboBox<>();
    panel4 = new JPanel();
    label1 = new JLabel();
    txtFileDir = new JTextField();
    panel5 = new JPanel();
    btnChangeDir = new JButton();
    panel1 = new JPanel();
    btnOk = new JButton();

    //======== this ========
    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle(bundle.getString("PreferencesDialog.this.title"));
    setAlwaysOnTop(true);
    var contentPane = getContentPane();
    contentPane.setLayout(new BorderLayout());

    //======== panel2 ========
    {
      panel2.setLayout(new GridBagLayout());
      ((GridBagLayout)panel2.getLayout()).columnWidths = new int[] {0, 0};
      ((GridBagLayout)panel2.getLayout()).rowHeights = new int[] {0, 0, 0, 0};
      ((GridBagLayout)panel2.getLayout()).columnWeights = new double[] {1.0, 1.0E-4};
      ((GridBagLayout)panel2.getLayout()).rowWeights = new double[] {1.0, 1.0, 1.0, 1.0E-4};

      //======== jPanel1 ========
      {
        jPanel1.setBorder(new TitledBorder(bundle.getString("PreferencesDialog.jPanel1.border")));
        jPanel1.setLayout(new FlowLayout(FlowLayout.LEFT));

        //---- cbxUpdates ----
        cbxUpdates.setText(bundle.getString("PreferencesDialog.cbxUpdates.text"));
        cbxUpdates.setBorder(BorderFactory.createEmptyBorder());
        cbxUpdates.setMargin(new Insets(0, 0, 0, 0));
        jPanel1.add(cbxUpdates);
      }
      panel2.add(jPanel1, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
        GridBagConstraints.CENTER, GridBagConstraints.BOTH,
        new Insets(0, 0, 0, 0), 0, 0));

      //======== jPanel3 ========
      {
        jPanel3.setBorder(new TitledBorder(bundle.getString("PreferencesDialog.jPanel3.border")));
        jPanel3.setLayout(new BorderLayout());

        //---- textArea2 ----
        textArea2.setBackground(UIManager.getColor("Label.background"));
        textArea2.setEditable(false);
        textArea2.setLineWrap(true);
        textArea2.setWrapStyleWord(true);
        textArea2.setText(bundle.getString("PreferencesDialog.textArea2.text"));
        jPanel3.add(textArea2, BorderLayout.CENTER);

        //======== panel3 ========
        {
          panel3.setLayout(new FlowLayout(FlowLayout.LEFT));

          //---- cmbFont ----
          cmbFont.setModel(new DefaultComboBoxModel<>(new String[] {
            "8",
            "10",
            "12",
            "14",
            "18",
            "20",
            "24",
            "30",
            "36"
          }));
          cmbFont.addActionListener(e -> cmbFontActionPerformed());
          panel3.add(cmbFont);
        }
        jPanel3.add(panel3, BorderLayout.LINE_START);
      }
      panel2.add(jPanel3, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
        GridBagConstraints.CENTER, GridBagConstraints.BOTH,
        new Insets(0, 0, 0, 0), 0, 0));

      //======== panel4 ========
      {
        panel4.setBorder(new TitledBorder(bundle.getString("PreferencesDialog.panel4.border")));
        panel4.setLayout(new GridBagLayout());
        ((GridBagLayout)panel4.getLayout()).columnWidths = new int[] {0, 0, 0};
        ((GridBagLayout)panel4.getLayout()).rowHeights = new int[] {0, 0, 0};
        ((GridBagLayout)panel4.getLayout()).columnWeights = new double[] {0.0, 1.0, 1.0E-4};
        ((GridBagLayout)panel4.getLayout()).rowWeights = new double[] {0.0, 0.0, 1.0E-4};

        //---- label1 ----
        label1.setText("File Directory");
        panel4.add(label1, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.BOTH,
          new Insets(3, 3, 3, 3), 0, 0));

        //---- txtFileDir ----
        txtFileDir.setEditable(false);
        panel4.add(txtFileDir, new GridBagConstraints(1, 0, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.BOTH,
          new Insets(0, 0, 0, 0), 0, 0));

        //======== panel5 ========
        {
          panel5.setLayout(new FlowLayout(FlowLayout.RIGHT));

          //---- btnChangeDir ----
          btnChangeDir.setText("Change Directory");
          btnChangeDir.addActionListener(e -> btnChangeDirActionPerformed());
          panel5.add(btnChangeDir);
        }
        panel4.add(panel5, new GridBagConstraints(1, 1, 1, 1, 0.0, 0.0,
          GridBagConstraints.CENTER, GridBagConstraints.BOTH,
          new Insets(0, 0, 0, 0), 0, 0));
      }
      panel2.add(panel4, new GridBagConstraints(0, 2, 1, 1, 0.0, 0.0,
        GridBagConstraints.CENTER, GridBagConstraints.BOTH,
        new Insets(0, 0, 0, 0), 0, 0));
    }
    contentPane.add(panel2, BorderLayout.CENTER);

    //======== panel1 ========
    {
      panel1.setLayout(new FlowLayout(FlowLayout.RIGHT));

      //---- btnOk ----
      btnOk.setText(bundle.getString("PreferencesDialog.btnOk.text"));
      btnOk.addActionListener(e -> btnOkActionPerformed());
      panel1.add(btnOk);
    }
    contentPane.add(panel1, BorderLayout.SOUTH);
    setSize(490, 370);
    setLocationRelativeTo(getOwner());
	}// </editor-fold>//GEN-END:initComponents


	/*
	 * Handle clicks on the OK button.
	 * When the user clicks on the OK button, settings will be saved,
	 * and the preferences dialog will be closed.
	 */
	private void btnOkActionPerformed() {//GEN-FIRST:event_btnOkActionPerformed
	  PropertyManager.getInstance().setProperty(PropertyManager.PROPERTY_CHECK_FOR_UPDATES,
        Boolean.toString(cbxUpdates.isSelected()));

		PropertyManager.getInstance().setProperty(PropertyManager.PROPERTY_FONT_SIZE,
        cmbFont.getSelectedItem().toString());

		this.setVisible(false);
		this.dispose();
	}//GEN-LAST:event_btnOkActionPerformed


	/*
	 * Respond to changes in the font size.
	 * When the user changes the font size, the size in all displayed tabs is updated.
	 */
	private void cmbFontActionPerformed() {//GEN-FIRST:event_cmbFontActionPerformed
		float size = 12f;

		try {
			size = Float.valueOf(this.cmbFont.getSelectedItem().toString());
		} catch (Exception e) {
			// ignore
		}

		List<TabPanel> tabs = ((MainWindow) this.getParent()).getTabList();
		if (tabs != null) {
      for (TabPanel tab : tabs) {
        tab.updateFontSize(size);
      }
    }
	}//GEN-LAST:event_cmbFontActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
  private JPanel panel2;
  private JPanel jPanel1;
  private JCheckBox cbxUpdates;
  private JPanel jPanel3;
  private JTextArea textArea2;
  private JPanel panel3;
  private JComboBox<String> cmbFont;
  private JPanel panel4;
  private JLabel label1;
  private JTextField txtFileDir;
  private JPanel panel5;
  private JButton btnChangeDir;
  private JPanel panel1;
  private JButton btnOk;
	// End of variables declaration//GEN-END:variables

}
